### ISSUE TITLE
Newly supported nodes/edges in core

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#110]
After 3.x upgrade, Cytoscape.js core should be supporting some nodes/edges that weren't there before such as necessary stimulation and rectangles with cutoff corners.
We should start using these asap to get rid of / reduce modifications to our Cytsocape.js instance.

**Comment by metincansiper** [comment]
I used 'triangle-cross' arrow shape supported by cytoscape.js core for rendering 'necessary stimulation'. However, we cannot use 'cutrectangle' shape for complexes for now, because complexes can have decorations (state variables and units of information) and they can be multimer (These features are not supported by cytoscape.js core yet).

**Comment by ugurdogrusoz** [comment]
Right, lets close this issue for now.
