### ISSUE TITLE
Selecting all objects of this type

### ISSUE THREAD

**Issue by mrsfy** [iVis-at-Bilkent/chise.js#13]
_From @ugurdogrusoz on June 16, 2016 11:39_

Once #137 is done, we can add a "Select All Objects of This Type" functionality to the context menus of nodes and edges.

_Copied from original issue: iVis-at-Bilkent/sbgnviz-js#138_

**Comment by mrsfy** [comment]
#12 should be done first to be able to add this functionality.

**Comment by metincansiper** [comment]
I added this functionality to ChiSE. I added the related menu item to the end for both nodes and edges. However, I realized that in default graph this operation takes time more than expected and select operation is the bottleneck here. I think that node-resize extension may be the cause of this performance problem.

**Comment by ugurdogrusoz** [comment]
Thanks. Can we change the menu item name to "Select Objects of This Type" to shorten it please? Then @mrsfy can look into the slowness issue since looks like there is indeed a problem with selection (node-resize extension). When we select all edges or node classes with lesser quantities, it's quick but if you select all simple chemicals or macromolecules in the default graph, it takes forever for the selection to finish.

**Comment by metincansiper** [comment]
I changed the menu item name to "Select Objects of This Type".
