### ISSUE TITLE
Listen ctrl+z and ctrl+y shortcuts from undo-redo extension

### ISSUE THREAD

**Issue by metincansiper** [iVis-at-Bilkent/chise.js#33]
In undo-redo extension these shortcuts can be listen optionally. Currently in ChiSE we set this option as false and listening these shortcuts in application level. We should listen them by using extension functionality.

**Comment by mrsfy** [comment]
I suggest that we should create a new extension for keyboard listening.
If this extension is based on [MouseTrap](https://craig.is/killing/mice) (which Max suggested), it would not require much effort compared to the fact that we need to solve followings.

Creating an extension can provide us following advantages:
- Incompatibility with other platforms like Mac would be solved.
- Creating/Deleting/Modifying a new shortcut would be more flexible. (I think it is important because editors like yEd have an ability to change shortcut keys as user desired.)
- We can add moving nodes by arrow keys to the extension itself.

**Comment by mrsfy** [comment]
Following extensions are now listening by mousetrap in application side:
undo-redo
clipboard
