### ISSUE TITLE
Cannot load this model

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#34]
The attached file cannot be loaded (throws an exception). It loads fine with the viewer SBGNViz 1.0 though (http://www.cs.bilkent.edu.tr/~ivis/SBGNViz.js/)!
[iNOSPD_SBGN-ED.sbgn.txt](https://github.com/iVis-at-Bilkent/chise.js/files/384342/iNOSPD_SBGN-ED.sbgn.txt)

**Comment by metincansiper** [comment]
This bug is related to cardinalities and probably it was emerging all graphs having edges with cardinalities. I fixed the bug and merged the change to unstable branch of sbgnviz too. I fixed the bug but I think that in long run we need to draw cardinality boxes using Cytoscape.js exposed API (Cytoscape.js is providing required functioanlity now).
