### ISSUE TITLE
Shortcut for Delete Selected Simple

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#40]
Can we map the "Delete" key as a shortcut for "Delete Selected Simple"?

**Comment by ugurdogrusoz** [comment]
It should be done in the same way with Ctrl-Z, etc. that we use in the application and in some extensions (e.g. undo extension).

**Comment by metincansiper** [comment]
I handled it in the same way with how Ctrl-Z, etc are handled in ChiSE.

**Comment by ugurdogrusoz** [comment]
Please do this in viewer as well.

**Comment by metincansiper** [comment]
In this issue it is specified that "It should be done in the same way with Ctrl-Z, etc. that we use in the application and in some extensions". In ChiSE I handled it in the same way with how Ctrl-Z, etc are handled in ChiSE. However, I think that currently I cannot do the same thing in the viewer because, the "moustrap" library is not used in the viewer. To solve this problem I can include the "mousetrap" in the viewer or I can implement the same function in the viewer in an other way. (I mean not in the same way with ChiSE. I can use native JS instead of Mousetrap to listen the shortcut as we do in some extensions)

**Comment by ugurdogrusoz** [comment]
Let's skip it for now. I am removing "Viewer as well" tag.
