### ISSUE TITLE
Default behavior for dragging in core

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#41]
When you left-click and drag in the root, it's panning by default (from Cytoscape.js). You need to use Shift or Ctrl for dragging to perform marquee/rectangle selection. Can we swap the two somehow? By default drag should map to selection not drag.

**Comment by metincansiper** [comment]
I found this section ( http://js.cytoscape.org/#notation/gestures ) in Cytoscape.js documentation. In thiis section the gestures in this issue are mentioned too. Also, I could not find any option to change the behaviour of them. Therefore, I think that this gestures may be fixed and it may not be possible to change their default behaviours without changing Cytoscape.js core code.

**Comment by ugurdogrusoz** [comment]
@maxkfranz Anyway we somehow can change this default behavior? We want the old behavior.

**Comment by maxkfranz** [comment]
The old behaviour was based on timing, and that's no longer supported at all.  It did not support pressing a key to enable box selection mode.  By and large, users did not discover or understand the timing feature.

Panning is default, because that's a standard gesture in lots of apps.  It's what users tend to expect.

The only way box selection becomes the default is if panning is disabled.  So, you can use a mode with a toggle -- maybe by a button.  Just disable panning when in your select mode.  You can make select mode default if you like.

**Comment by ugurdogrusoz** [comment]
Let's close this since it looks like it is not straightforward to change default Cytoscape.js behavior.
