### ISSUE TITLE
Font not resized on undo of node resize

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#51]
- Resize a node to be bigger (font size increases accordingly)
- Undo the resize; font size will not decrease back to the original unless you refresh (e.g. mouse over)

**Comment by metincansiper** [comment]
The problem seems to be fixed now. However, while solving this problem I recognized an issue related to node-resize extension and I filed that issue ( https://github.com/iVis-at-Bilkent/cytoscape.js-node-resize/issues/4 ). 

If some changes related to the above issue are done in that extension, we may need (I am not sure) little code changes related to this issue.
