### ISSUE TITLE
Use edge labels for drawing cardinality

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#52]
Use the enhanced edge label feature of Cytoscape.js core to implement cardinality for some edge types rather than changing core code.

**Comment by metincansiper** [comment]
Now we draw cardinalities by using Cytoscape.js core facilities. In consumption edges the cardinality boxes are 15% away from the source while they are 15% away from the target in production edges. However, I think that the solution I used to preserve 15% dynamically may be improved. I opened this issue ( https://github.com/cytoscape/cytoscape.js/issues/1497 ) to learn if such an improvement is possible.

**Comment by ugurdogrusoz** [comment]
Can we make the background of these rectangles white with no transparency please? In cases, where the cardinality is overlapping with the edge line, we don't want the edge crossing through the cardinality.

**Comment by metincansiper** [comment]
@ugurdogrusoz I think the reason why the performance of node drag is decreased is some code in this issue. As it is mentioned in my previous comment the solution I used to preserve 15% dynamically is not good in terms of performance (However, I was not expecting such an important performance decrease). The problem was that we were updating the style to redraw the graph on node drag to preserve the 15% dynamically (I realized that in that sense such a performance decrease is expected). With my last commit we are updating the style on 'tapend' instead of 'drag', in this way we get rid of the performance decrease but the position of cardinality boxes are updated on 'tapend' instead of 'drag'. Is this something undesired?

**Comment by metincansiper** [comment]
@ugurdogrusoz I made the background of cardinality boxes white with no transparency.

**Comment by ugurdogrusoz** [comment]
Could we transfer this to the viewer as well please?

**Comment by metincansiper** [comment]
We use edge labels for drawing cardinality in viewer as well. Also, currently in chise/newt we inherit this feature from sbgnviz.

**Comment by ugurdogrusoz** [comment]
This is not exactly what we like but that's the best we can do with provided Cytoscape.js functionality.
