### ISSUE TITLE
Better control of adjusting node font size

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#53]
Currently node font sizes are calculated based on node dimensions and adjusted automatically upon resize of the node. However, certain users might want to control the font sizes manually. Thus we should have an option under Properties named "Adjust Node Label Font Size Automatically", which is false by default. When this is not checked, the node labels should be given fixed default font sizes and they should not be changed when the node is resized. However, the user should have the option to change the font size from the inspector themselves.

**Comment by metincansiper** [comment]
Yes there is 'expandCollapseCuePosition' option for this purpose. However, I realized that this feature was buggy and I fixed the related bug. It must be working well in version '1.1.2'. 

For example if you want the cues to be rendered at the node centers it can be used in the following way:

      expandCollapseCuePosition: function(ele) {
            return ele.position()
      }

**Comment by metincansiper** [comment]
I implemented this feature as it is desired in this issue except one thing. I have not set the default value of "Adjust Node Label Font Size Automatically" as "false" yet. When I set it to 'false' the default look of the graphs change as we use some default values for the label sizes of nodes instead of calculating them. Therefore, I wanted to show the looks of the graphs when this option is 'false' and 'true' and ask whether I should set the default value of this flag as 'false'. 

- When the option is 'true'
![capture](https://cloud.githubusercontent.com/assets/6534865/18672305/568a1f84-7f50-11e6-8718-9d2f05ea7b28.PNG)

- When the option is 'false'
![capture2](https://cloud.githubusercontent.com/assets/6534865/18672340/730736ce-7f50-11e6-9f69-0cc3693fdb11.PNG)

**Comment by ugurdogrusoz** [comment]
Great! Let's just update one or two samples whose default node sizes are not compatible with the default font size (nodes are too small) and then turn off that option.

**Comment by metincansiper** [comment]
I have updated two samples (atm_mediated_phosphorylation_of_repair_proteins and vitamins_b6_activation_to_pyridoxal_phosphate) as described and turned off that option.

**Comment by ugurdogrusoz** [comment]
Great! The only thing I noticed is that Font related properties are not recorded when the user choose "Set as Default for ..." in the inspector.

**Comment by metincansiper** [comment]
I recorded font related properties upon "Set as Default for ..." in the inspector.
