### ISSUE TITLE
Phenotypes cannot be connected to any node

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#69]
Current implementation doesn't allow phenotypes to be connected to any type of node with any type of interactions. They should be allowed to connect to any type of node processes are.

**Comment by metincansiper** [comment]
I realized that in section 2.3 of the document in the following link ( 'https://github.com/sbgn/process-descriptions/blob/master/UserManual/sbgn_PD-level1-user-public.pdf' ) it is stated that 'phenotype' is a member of Process Node's. I think that in Chise we have not defined phenotype as a PN and so we had this issue. Now, I defined phenotype as a PN and the problem seems to be solved.
